<?xml version='1.0' encoding ='ISO-8859-1' standalone='yes' ?>
<!DOCTYPE corpus[
      <!-- début de la DTD -->
      <!ELEMENT CORPUS (PAGE_LCI+)>
	<!ELEMENT PAGE_LCI (FICHIER,DATE_PAGE,UNE?,LES_VOIRAUSSI*,FOCUS?,LES_GROSTITRES*,LES_RAPPELS*)>
	<!ELEMENT UNE (urlArticle?|titreArticle?|dateArticle?|urlImage?|resumeArticle?|mailto?|auteur?)>
	<!ELEMENT LES_VOIRAUSSI (VOIRAUSSI+)>
	<!ELEMENT LES_GROSTITRES (GROSTITRE+)>
	<!ELEMENT LES_RAPPELS (RAPPEL+)>
	<!ELEMENT VOIRAUSSI (urlArticle|titreArticle|dateArticle)>
	<!ELEMENT FOCUS (urlArticle?|titreArticle?|dateArticle?|urlImage?|resumeArticle?|mailto?|auteur?)>
	<!ELEMENT GROSTITRE (urlArticle?|themeArticle?|titreArticle?|dateArticle?|urlImage?|resumeArticle?|mailto?|auteur?)>
	<!ELEMENT RAPPEL (urlArticle?|themeArticle?|titreArticle?|dateArticle?)>
	<!ELEMENT urlArticle (#PCDATA) >
	<!ELEMENT urlImage (#PCDATA) >
	<!ELEMENT themeArticle (#PCDATA) >
	<!ELEMENT dateArticle (#PCDATA) >
	<!ELEMENT resumeArticle (#PCDATA) >
	<!ELEMENT mailto (#PCDATA) >
	<!ELEMENT auteur (#PCDATA) >
	<!ELEMENT titreArticle (#PCDATA) >
	<!ELEMENT FICHIER (#PCDATA) >
	<!ELEMENT DATE_PAGE (#PCDATA) >
      <!-- fin de la DTD -->
]>
<CORPUS>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-02-25.html</FICHIER>
<DATE_PAGE>25/02/2005</DATE_PAGE>
<UNE>
<dateArticle>25/02/2005</dateArticle>
<urlArticle>news/monde/0,,3204466-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> pape muet</titreArticle>
<urlImage>s.tf1.fr/mmdia/i/47/7/2018477_5.jpg</urlImage>
<resumeArticle> pape  subi    trachéotomie  aider  respir. acte chirurgical  duré 30 minute. opération laiss toutefois  souverain pontif sans voix,   risque  relanc  question   démission.</resumeArticle>
<mailto>dstraus@tf1.fr</mailto>
<auteur>D.S. (d'après AFP)</auteur>
</UNE>
<LES_VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,3204267-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>jean-paul ii opér " succ"</titreArticle>
<dateArticle>24/02/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/economie/0,,3204457-VU5WX0lEIDUy,00.html',700,600,52);"></urlArticle>
<titreArticle>inquiét  catholique  monde entier</titreArticle>
<dateArticle>24/02/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/economie/0,,3204461-VU5WX0lEIDUy,00.html',700,600,52);"></urlArticle>
<titreArticle> peut-  passer si  pape  incapa assurer  tâche ?</titreArticle>
<dateArticle>24/02/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/economie/0,,3204462-VU5WX0lEIDUy,00.html',700,600,52);"></urlArticle>
<titreArticle>retour   santé  pape ces  dernière semaine</titreArticle>
<dateArticle>24/02/2005</dateArticle>
</VOIRAUSSI>
</LES_VOIRAUSSI>
<FOCUS>
<dateArticle>25/02/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/52/7/2018527_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204381-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>/poutine : ambiance glacial  bratislava</titreArticle>
<resumeArticle>coup  froid   sommet améri-russe  bratislava :  présence même   homologue  face   presse, george w.   dit "préoccup"  état   démocrat  russie. " démocrat,    anarchi"  répon vladimir poutine, très tendu.</resumeArticle>
<mailto>agautier@tf1.fr</mailto>
<auteur>A.Ga. (d'après AFP)</auteur>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/42/9/1027429_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204369-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Italie</themeArticle>
<titreArticle>berlusconi   collimateur   justice</titreArticle>
<resumeArticle>plusieurs témoign accabl    itali soupçonné évasion fiscal  abus  bien sociaux. david mills, ancien homme  loi  berlusconi aurait ainsi créé  société offshore  nom  enfant  chef  gouvernement afin  aider  transfér  argent  étranger.</resumeArticle>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/02/9/2016029_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204252-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Procès</themeArticle>
<titreArticle> jury très fémini  mich jackson</titreArticle>
<resumeArticle> douze membre  jury chargé  juger mich jackson   désign. huit femme  font partie  aucun noir   reten.  star   pop  notamment accusée agression sexuel   mineur  13 .</resumeArticle>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/02/6/2016026_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204274-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Irak</themeArticle>
<titreArticle>florence  hussein "toujours vivant"</titreArticle>
<resumeArticle>associ report sans front annon  florence aube  hussein hanoun seraient "toujours vivant". cela  cinquant jours   journaliste   guide  dispar  irak.</resumeArticle>
<mailto>stgnews@tf1.fr</mailto>
<auteur>avec AFP</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/47/7/2018477_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204267-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Vatican</themeArticle>
<titreArticle>jean-paul ii opér " succ"</titreArticle>
<resumeArticle> pape  subi    trachéotomie  aider  respir. agé  84 ,  souverain pontif   hospitali  urgen   second fois   mois  hôpita gemelli  rome   suite  problème respirat.  prochain bulletin  santé  prévu   fin  matinée.</resumeArticle>
<mailto>agautier@tf1.fr</mailto>
<auteur>A.Ga. (d'après AFP)</auteur>
</GROSTITRE>
</LES_GROSTITRES>
<LES_RAPPELS>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Rencontre</themeArticle>
<urlArticle>news/monde/0,,3204172-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>  pression   syri</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Vatican</themeArticle>
<urlArticle>news/monde/0,,3204078-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>viol polémique autour  livre  pape</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Colombie</themeArticle>
<urlArticle>news/monde/0,,3204086-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>betancourt, otage   </titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Bush - Poutine</themeArticle>
<urlArticle>news/monde/0,,3204192-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>face  face tendu</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>R.U.</themeArticle>
<urlArticle>news/people/0,,3204075-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>camouflet royal  charles  camill</titreArticle>
</RAPPEL>
</LES_RAPPELS>
</PAGE_LCI>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-02-27.html</FICHIER>
<DATE_PAGE>27/02/2005</DATE_PAGE>
<UNE>
<dateArticle>27/02/2005</dateArticle>
<urlArticle>news/monde/0,,3204809-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> brève appar  jean-paul ii</titreArticle>
<urlImage>s.tf1.fr/mmdia/i/70/0/2018700_5.jpg</urlImage>
<resumeArticle> pape  béni  foule  sign   croix   chambre   hôpita gemelli  rome.   première fois  jean-paul ii  présid   prière  angélus.   message lu   nom  archevêque leonardo sandr,   demand  fidèle  prier  lui.  souverain pontif âgé  84   hospitali    avoir subi  trachéotomie.</resumeArticle>
<mailto>agautier@tf1.fr</mailto>
<auteur>A.Ga. (d'après AFP)</auteur>
</UNE>
<LES_VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,3204267-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>jean-paul ii opér " succ"</titreArticle>
<dateArticle>24/02/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,3204466-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> pape restera muet plusieurs jours</titreArticle>
<dateArticle>25/02/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/economie/0,,3204798-VU5WX0lEIDUy,00.html',700,600,52);"></urlArticle>
<titreArticle> point  état  santé  jean-paul ii</titreArticle>
<dateArticle>26/02/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/economie/0,,3204848-VU5WX0lEIDUy,00.html',700,600,52);"></urlArticle>
<titreArticle>appar surprise  pape</titreArticle>
<dateArticle>27/02/2005</dateArticle>
</VOIRAUSSI>
</LES_VOIRAUSSI>
<FOCUS>
<dateArticle>27/02/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/69/8/2018698_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204806-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> demi-frère  saddam hussein arrêt</titreArticle>
<resumeArticle>sabaoui ibrahim al-hassan, ex leader baasiste,  soupçonné  dirig  rébellion   gouvernement irakien.</resumeArticle>
<mailto>dstraus@tf1.fr</mailto>
<auteur>D.S. (avec AFP)</auteur>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/65/6/2018656_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204661-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Proche-Orient</themeArticle>
<titreArticle> jihad revendiqu attentat  tel-aviv</titreArticle>
<resumeArticle> mouvement accuse autori palestinien  "collabor"  israël.     défense israélien met  cause  responsabilité   syri.</resumeArticle>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/67/8/2018678_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204733-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>USA</themeArticle>
<titreArticle> fin  myst autour  tueur  série</titreArticle>
<resumeArticle> police  kansas  arrêt  tueur particulière sadique  terroris  habitant  cet état américain    30 . homme aurait tortur  tué huit personn entre 1974  1986.</resumeArticle>
<mailto>agautier@tf1.fr</mailto>
<auteur>A.Ga.</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/65/8/2018658_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204664-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Togo</themeArticle>
<titreArticle>gnassingbé rend  fauteuil présid</titreArticle>
<resumeArticle> nouve homme fort  togo, fils   défunt,  plié   souhait   commun internationa.</resumeArticle>
<mailto>dstraus@tf1.fr</mailto>
<auteur>D.S. (avec AFP)</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/47/7/2018477_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204466-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Vatican</themeArticle>
<titreArticle> pape restera muet plusieurs jours</titreArticle>
<resumeArticle>  vatican,  souverain pontif respir sans assistance.   passé  nuit calme  lendemain  trachéotomie subie " succ"   suite  diff respirat.</resumeArticle>
</GROSTITRE>
</LES_GROSTITRES>
<LES_RAPPELS>
<RAPPEL>
<dateArticle>26/02/2005</dateArticle>
<themeArticle>Italie</themeArticle>
<urlArticle>news/monde/0,,3204731-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> forcené maîtr   carabiniers</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>24/02/2005</dateArticle>
<themeArticle>Italie</themeArticle>
<urlArticle>news/monde/0,,3204369-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>berlusconi   collimateur   justice</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>24/02/2005</dateArticle>
<themeArticle>Procès</themeArticle>
<urlArticle>news/monde/0,,3204252-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> jury très fémini  mich jackson</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>24/02/2005</dateArticle>
<themeArticle>Irak</themeArticle>
<urlArticle>news/monde/0,,3204274-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>florence  hussein "toujours vivant"</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>24/02/2005</dateArticle>
<themeArticle>Vatican</themeArticle>
<urlArticle>news/monde/0,,3204267-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>jean-paul ii opér " succ"</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Rencontre</themeArticle>
<urlArticle>news/monde/0,,3204172-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>  pression   syri</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Vatican</themeArticle>
<urlArticle>news/monde/0,,3204078-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>viol polémique autour  livre  pape</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Colombie</themeArticle>
<urlArticle>news/monde/0,,3204086-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>betancourt, otage   </titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Bush - Poutine</themeArticle>
<urlArticle>news/monde/0,,3204192-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>face  face tendu</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>R.U.</themeArticle>
<urlArticle>news/people/0,,3204075-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>camouflet royal  charles  camill</titreArticle>
</RAPPEL>
</LES_RAPPELS>
</PAGE_LCI>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-02-28.html</FICHIER>
<DATE_PAGE>28/02/2005</DATE_PAGE>
<UNE>
<dateArticle>28/02/2005</dateArticle>
<urlArticle>news/monde/0,,3204922-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> millier  libanais défient  pouvoir</titreArticle>
<urlImage>s.tf1.fr/mmdia/i/73/8/2018738_5.jpg</urlImage>
<resumeArticle>bravant interdi  pouvoir,  millier  libanais  rassembl  aube  beyrouth. ils répon  appel  opposition  déposé  parlement  motion  censure   cabine pro-syri.</resumeArticle>
</UNE>
<FOCUS>
<dateArticle>28/02/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/50/7/2018507_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204931-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>ue : posez vos question  daniel cohn-bendit</titreArticle>
<resumeArticle> député euro sera invit    13h30  notre  chat consacr   ratifi   constitu euro. vous pouvez lui poser vos question dès mainten.</resumeArticle>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/71/2/2018712_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204940-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Vatican</themeArticle>
<titreArticle> pape " bonne condition générale"</titreArticle>
<resumeArticle>  dernier bulletin  santé  pape, jean-paul ii  remet bien   trachéotomie   subie  semaine dernière.   commencé  exercice  rééducation   respirat    parole.</resumeArticle>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/76/2/2018762_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204934-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Irak</themeArticle>
<titreArticle>  100    nouve attentat</titreArticle>
<resumeArticle>110 personn   tuées  133 bless     attentat suicid  hill,  vill située  100 km  sud  bagdad.</resumeArticle>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/02/9/2016029_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204805-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Etats-Unis</themeArticle>
<titreArticle>mich jackson va pouvoir expliqu</titreArticle>
<resumeArticle> chanteu va pouvoir commencer   répon  accusation agression sexuel   mineur, lors   procès  santa maria (californie).</resumeArticle>
<mailto>dstraus@tf1.fr</mailto>
<auteur>AFP</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/71/3/2018713_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204852-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>P-O</themeArticle>
<titreArticle>avertissement  sharon  palestinien</titreArticle>
<resumeArticle>   israël  sommé  autori palestinien  "combat  terroris"   mis  cause  syri  attentat commis   tel-aviv.   syri  affaire étrangère  nié toute implication      insinué  rôle israël  attaqu suicid.</resumeArticle>
<mailto>agautier@tf1.fr</mailto>
<auteur>A.Ga. (avec AFP)</auteur>
</GROSTITRE>
</LES_GROSTITRES>
<LES_RAPPELS>
<RAPPEL>
<dateArticle>27/02/2005</dateArticle>
<themeArticle>Vatican</themeArticle>
<urlArticle>news/monde/0,,3204809-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> sign  pape   fidèle</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>27/02/2005</dateArticle>
<themeArticle>Irak</themeArticle>
<urlArticle>news/monde/0,,3204806-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> demi-frère  saddam hussein arrêt</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>26/02/2005</dateArticle>
<themeArticle>P-O</themeArticle>
<urlArticle>news/monde/0,,3204661-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> jihad revendiqu attentat  tel-aviv</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>26/02/2005</dateArticle>
<themeArticle>USA</themeArticle>
<urlArticle>news/monde/0,,3204733-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> fin  myst autour  tueur  série</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>26/02/2005</dateArticle>
<themeArticle>Togo</themeArticle>
<urlArticle>news/monde/0,,3204664-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>gnassingbé rend  fauteuil présid</titreArticle>
</RAPPEL>
</LES_RAPPELS>
</PAGE_LCI>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-03-01.html</FICHIER>
<DATE_PAGE>01/03/2005</DATE_PAGE>
<UNE>
<dateArticle>01/03/2005</dateArticle>
<urlArticle>news/monde/0,,3205126-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> vidéo  florence aube</titreArticle>
<urlImage>s.tf1.fr/mmdia/i/86/3/2018863_5.jpg</urlImage>
<resumeArticle>  enregistrement vidéo diff  irak mais non daté,  journaliste  libér, dispar   5 janvier, appel  aide. "ma santé  très mauvais. je suis également très mal  plan psychologique. aidez-moi,  urgen" lance-t-elle. elle demand notamment appui  député ump didier julia,  origine  polémique lors  affaire  précédent otage , george malbrunot  christian chesnot.</resumeArticle>
</UNE>
<LES_VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,3200672-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>aube,  mois déjà</titreArticle>
<dateArticle>05/02/2005</dateArticle>
</VOIRAUSSI>
</LES_VOIRAUSSI>
<FOCUS>
<dateArticle>01/03/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/50/7/2018507_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204931-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>ue : posez vos question  daniel cohn-bendit</titreArticle>
<resumeArticle> député euro sera invit    13h30  notre  chat consacr   ratifi   constitu euro. vous pouvez lui poser vos question dès mainten.</resumeArticle>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/86/0/2018860_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205127-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Allemagne</themeArticle>
<titreArticle>polémique  ouvert  hôte   nid aigle hitl</titreArticle>
<resumeArticle>  uns,  occasion  donner   souff  touris loca,   autres,  mélan  genre  scandale.</resumeArticle>
<mailto>aguillet@tf1.fr</mailto>
<auteur>AG (avec AFP)</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/85/8/2018858_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205124-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Michael Jackson</themeArticle>
<titreArticle>premier détail  procès</titreArticle>
<resumeArticle>  mois consacr   sélection  jury,  procès  chanteu  véritable débuté     lecture  arrêt  renvoi   première accusation concrètes  procureur.</resumeArticle>
<mailto>faubert@tf1.fr</mailto>
<auteur>F.A., avec AFP</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/81/5/2018815_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205033-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Liban</themeArticle>
<titreArticle> rue  chute  pouvoir</titreArticle>
<resumeArticle>   libanais omar karamé  annon, ,  démission alors   parlement devait examin  motion  censure déposée  opposition anti-syrienne    millier  personn défilaient  beyrouth.</resumeArticle>
</GROSTITRE>
</LES_GROSTITRES>
<LES_RAPPELS>
<RAPPEL>
<dateArticle>28/02/2005</dateArticle>
<themeArticle>Irak</themeArticle>
<urlArticle>news/monde/0,,3204934-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>  100    nouve attentat</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>28/02/2005</dateArticle>
<themeArticle>Vatican</themeArticle>
<urlArticle>news/monde/0,,3204940-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> pape " bonne condition générale"</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>27/02/2005</dateArticle>
<themeArticle>P-O</themeArticle>
<urlArticle>news/monde/0,,3204852-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>avertissement  sharon  palestinien</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>27/02/2005</dateArticle>
<themeArticle>Irak</themeArticle>
<urlArticle>news/monde/0,,3204806-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> demi-frère  saddam hussein arrêt</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>26/02/2005</dateArticle>
<themeArticle>P-O</themeArticle>
<urlArticle>news/monde/0,,3204661-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> jihad revendiqu attentat  tel-aviv</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>26/02/2005</dateArticle>
<themeArticle>USA</themeArticle>
<urlArticle>news/monde/0,,3204733-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> fin  myst autour  tueur  série</titreArticle>
</RAPPEL>
</LES_RAPPELS>
</PAGE_LCI>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-03-03.html</FICHIER>
<DATE_PAGE>03/03/2005</DATE_PAGE>
<UNE>
<dateArticle>03/03/2005</dateArticle>
<urlArticle>news/monde/0,,3205560-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>bali : pein légère  bachir</titreArticle>
<urlImage>s.tf1.fr/mmdia/i/99/8/538998_5.jpg</urlImage>
<resumeArticle> chef religieu indonésie abou bakar bachir   condamn       demi  prison ferme   rôle   attentat  bali  2002.    revanch  blanc  affaire  attaqu  hôte marriott  jakarta  2003.</resumeArticle>
</UNE>
<LES_VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,960358-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>bali :  suspect avoue</titreArticle>
<dateArticle>08/11/2002</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,964955-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> cerveau  attentat  bali passe  aveux</titreArticle>
<dateArticle>22/11/2002</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,1062351-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>début  procès  attentat  bali</titreArticle>
<dateArticle>12/05/2003</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,1350143-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>bali : deuxième condamn  mort</titreArticle>
<dateArticle>10/09/2003</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,3180247-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> islam bachir inculp   attentat  bali</titreArticle>
<dateArticle>16/10/2004</dateArticle>
</VOIRAUSSI>
</LES_VOIRAUSSI>
<FOCUS>
<dateArticle>03/03/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/85/0/874850_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205442-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> "jilbab" islam autori  école</titreArticle>
<resumeArticle>  longue bataille judiciaire,  lycée musulman  obten  droit  porter  école  "jilbab",  longue robe   laiss voir   mains   visage. elle était défendue  cherie blair,  femme   .</resumeArticle>
<mailto>faubert@tf1.fr</mailto>
<auteur>Fabrice AUBERT</auteur>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/24/1/2019241_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205642-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Aubenas</themeArticle>
<titreArticle>julia pose  condition</titreArticle>
<resumeArticle>sollicit     , didier julia  indiqu  avoir eu  entretien   direct général   dgse   cas  florence aube. mais,  préalable   coopér,  réclam  levée  contrôl judiciaire   collabor.</resumeArticle>
</GROSTITRE>
</LES_GROSTITRES>
<LES_RAPPELS>
<RAPPEL>
<dateArticle>02/03/2005</dateArticle>
<themeArticle>Aubenas</themeArticle>
<urlArticle>news/monde/0,,3205475-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>raffarin demand  julia  collabor</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>01/03/2005</dateArticle>
<themeArticle>Procès Jackson</themeArticle>
<urlArticle>news/monde/0,,3205325-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>audition  témoi crucial</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>02/03/2005</dateArticle>
<themeArticle>Liban</themeArticle>
<urlArticle>news/monde/0,,3205333-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> syri promet   retirer</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>01/03/2005</dateArticle>
<themeArticle>USA</themeArticle>
<urlArticle>news/monde/0,,3205249-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> mineur  seron  exécut</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>01/03/2005</dateArticle>
<themeArticle>Allemagne</themeArticle>
<urlArticle>news/monde/0,,3205127-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>polémique  ouvert  hôte   nid aigle hitl</titreArticle>
</RAPPEL>
</LES_RAPPELS>
</PAGE_LCI>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-03-04.html</FICHIER>
<DATE_PAGE>04/03/2005</DATE_PAGE>
<UNE>
<dateArticle>04/03/2005</dateArticle>
<urlArticle>news/monde/0,,3205754-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>ukrain : ex-  intérieur retrouv suicid</titreArticle>
<urlImage>s.tf1.fr/mmdia/i/29/4/2019294_5.gif"</urlImage>
<resumeArticle>iouri kravtchenko devait témoign     cadre  affaire  assassin  journaliste opposition gueorgui gongadzé.    retrouv mort,   appar tiré  balle   tête.</resumeArticle>
</UNE>
<FOCUS>
<dateArticle>04/03/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/50/7/2018507_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205649-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>cohn-bendit : "euro, dernière utopie"</titreArticle>
<resumeArticle>invit    notre  chat consacr  référendum   constitu,  député euro écologiste  dit confian   victoire  "oui".  lui, euro   effet  "dernière utopie  laquelle on méri   battre".</resumeArticle>
<mailto>faubert@tf1.fr</mailto>
<auteur>Fabrice AUBERT et R.P.</auteur>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/54/1/19541_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205751-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Italie</themeArticle>
<titreArticle> famille, rempart  exclusi</titreArticle>
<resumeArticle> itali,  notamment  rome,  grande majorit  sans-abris   immigr.  lien familial  amical jouant  effet  rôle  bouclier  exclusi,   très rare   itali  retrouv   rue.</resumeArticle>
<mailto>faubert@tf1.fr</mailto>
<auteur>Maurice OLIVARI</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/25/9/2019259_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205642-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Aubenas</themeArticle>
<titreArticle>appel  raffarin  ravisseur aube</titreArticle>
<resumeArticle>   , toute demand  didier julia agir " manière indépendan"  faveur  florence aube  "inacceptable". élu ump ainsi écart, jean-pierre raffarin, adress  ravisseur, leur  demand   contact " seuls service officiel   "  "engag  discussions".</resumeArticle>
</GROSTITRE>
</LES_GROSTITRES>
<LES_RAPPELS>
<RAPPEL>
<dateArticle>03/03/2005</dateArticle>
<themeArticle>Attentat de Bali</themeArticle>
<urlArticle>news/monde/0,,3205560-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>pein légère  bachir</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>02/03/2005</dateArticle>
<themeArticle>Royaume-Uni</themeArticle>
<urlArticle>news/monde/0,,3205442-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> "jilbab" islam autori  école</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>01/03/2005</dateArticle>
<themeArticle>USA</themeArticle>
<urlArticle>news/monde/0,,3205249-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> mineur  seron  exécut</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>01/03/2005</dateArticle>
<themeArticle>Allemagne</themeArticle>
<urlArticle>news/monde/0,,3205127-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>polémique  ouvert  hôte   nid aigle hitl</titreArticle>
</RAPPEL>
</LES_RAPPELS>
</PAGE_LCI>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-03-05.html</FICHIER>
<DATE_PAGE>05/03/2005</DATE_PAGE>
<UNE>
<dateArticle>05/03/2005</dateArticle>
<urlArticle>news/monde/0,,3205941-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> vie sauvée,  vie perdue</titreArticle>
<urlImage>s.tf1.fr/mmdia/i/40/1/2019401_5.jpg</urlImage>
<resumeArticle> joie   libér  giuli sgrena, reten  otage duran  mois  irak,   endeuillée   mort    libér tué   tirs américain,  membre  service spéc  traité  "héros" samedi   presse   péninsule.  journaliste  arrivée samedi   itali où elle doit  réopérée   clavicule.</resumeArticle>
<mailto>dstraus@tf1.fr</mailto>
<auteur>AFP</auteur>
</UNE>
<LES_VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,3205861-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>libér chaotique  giuli sgrena</titreArticle>
<dateArticle>04/03/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/newsthemes/monde/0,,3205869-VU5WX0lEIDUy,00.html',740,580,52);"></urlArticle>
<titreArticle>giuli sgrena libre</titreArticle>
<dateArticle>04/03/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/newsthemes/france/0,,3205875-VU5WX0lEIDUy,00.html',740,580,52);"></urlArticle>
<titreArticle>retour   mobilis  florence aube</titreArticle>
<dateArticle>04/03/2005</dateArticle>
</VOIRAUSSI>
</LES_VOIRAUSSI>
<FOCUS>
<dateArticle>05/03/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/50/7/2018507_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205649-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>cohn-bendit : "euro, dernière utopie"</titreArticle>
<resumeArticle>invit    notre  chat consacr  référendum   constitu,  député euro écologiste  dit confian   victoire  "oui".  lui, euro   effet  "dernière utopie  laquelle on méri   battre".</resumeArticle>
<mailto>faubert@tf1.fr</mailto>
<auteur>Fabrice AUBERT et R.P.</auteur>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/69/1/851691_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205944-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Côté d'Ivoire</themeArticle>
<titreArticle> soldat  tués accident</titreArticle>
<resumeArticle>  hommes  perdu  vie  explosion accident  loca  muni  abidjan.  troisième   grièvement bless.</resumeArticle>
<mailto>dstraus@tf1.fr</mailto>
<auteur>David STRAUS</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/46/1/2016461_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205861-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Irak</themeArticle>
<titreArticle>libér chaotique  giuli sgrena</titreArticle>
<resumeArticle> convoi  amenait  journaliste italienne  aéroport  bagdad    cibl  tirs   coalition,  . légère bless  épaule, elle venai  libér.</resumeArticle>
<mailto>dstraus@tf1.fr</mailto>
<auteur>D.S.</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/29/4/2019294_2.gif"</urlImage>
<urlArticle>news/monde/0,,3205754-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Ukraine</themeArticle>