<?xml version='1.0' encoding ='ISO-8859-1' standalone='yes' ?>
<!DOCTYPE corpus[
      <!-- début de la DTD -->
      <!ELEMENT CORPUS (PAGE_LCI+)>
	<!ELEMENT PAGE_LCI (FICHIER,DATE_PAGE,UNE?,LES_VOIRAUSSI*,FOCUS?,LES_GROSTITRES*,LES_RAPPELS*)>
	<!ELEMENT UNE (urlArticle?|titreArticle?|dateArticle?|urlImage?|resumeArticle?|mailto?|auteur?)>
	<!ELEMENT LES_VOIRAUSSI (VOIRAUSSI+)>
	<!ELEMENT LES_GROSTITRES (GROSTITRE+)>
	<!ELEMENT LES_RAPPELS (RAPPEL+)>
	<!ELEMENT VOIRAUSSI (urlArticle|titreArticle|dateArticle)>
	<!ELEMENT FOCUS (urlArticle?|titreArticle?|dateArticle?|urlImage?|resumeArticle?|mailto?|auteur?)>
	<!ELEMENT GROSTITRE (urlArticle?|themeArticle?|titreArticle?|dateArticle?|urlImage?|resumeArticle?|mailto?|auteur?)>
	<!ELEMENT RAPPEL (urlArticle?|themeArticle?|titreArticle?|dateArticle?)>
	<!ELEMENT urlArticle (#PCDATA) >
	<!ELEMENT urlImage (#PCDATA) >
	<!ELEMENT themeArticle (#PCDATA) >
	<!ELEMENT dateArticle (#PCDATA) >
	<!ELEMENT resumeArticle (#PCDATA) >
	<!ELEMENT mailto (#PCDATA) >
	<!ELEMENT auteur (#PCDATA) >
	<!ELEMENT titreArticle (#PCDATA) >
	<!ELEMENT FICHIER (#PCDATA) >
	<!ELEMENT DATE_PAGE (#PCDATA) >
      <!-- fin de la DTD -->
]>
<CORPUS>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-02-25.html</FICHIER>
<DATE_PAGE>25/02/2005</DATE_PAGE>
<UNE>
<dateArticle>25/02/2005</dateArticle>
<urlArticle>news/monde/0,,3204466-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> pape muet</titreArticle>
<urlImage>s.tf1.fr/mmdia/i/47/7/2018477_5.jpg</urlImage>
<resumeArticle> pape  subi    trachéotomie  aider  respirer. acte chirurgical  duré 30 minutes. opération laisse toutefois  souverain pontife sans voix,   risque  relancer  question   démission.</resumeArticle>
<mailto>dstraus@tf1.fr</mailto>
<auteur>D.S. (d'après AFP)</auteur>
</UNE>
<LES_VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,3204267-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>jean-paul ii opéré " succès"</titreArticle>
<dateArticle>24/02/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/economie/0,,3204457-VU5WX0lEIDUy,00.html',700,600,52);"></urlArticle>
<titreArticle>inquiétude  catholiques  monde entier</titreArticle>
<dateArticle>24/02/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/economie/0,,3204461-VU5WX0lEIDUy,00.html',700,600,52);"></urlArticle>
<titreArticle> peut-  passer si  pape  incapable assurer  tâche ?</titreArticle>
<dateArticle>24/02/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/economie/0,,3204462-VU5WX0lEIDUy,00.html',700,600,52);"></urlArticle>
<titreArticle>retour   santé  pape ces  dernières semaines</titreArticle>
<dateArticle>24/02/2005</dateArticle>
</VOIRAUSSI>
</LES_VOIRAUSSI>
<FOCUS>
<dateArticle>25/02/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/52/7/2018527_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204381-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>/poutine : ambiance glaciale  bratislava</titreArticle>
<resumeArticle>coup  froid   sommet américano-russe  bratislava :  présence même   homologue  face   presse, george w.   dit "préoccupé"  état   démocratie  russie. " démocratie,    anarchie"  répondu vladimir poutine, très tendu.</resumeArticle>
<mailto>agautier@tf1.fr</mailto>
<auteur>A.Ga. (d'après AFP)</auteur>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/42/9/1027429_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204369-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Italie</themeArticle>
<titreArticle>berlusconi   collimateur   justice</titreArticle>
<resumeArticle>plusieurs témoignages accablent    italien soupçonné évasion fiscale  abus  bien sociaux. david mills, ancien homme  loi  berlusconi aurait ainsi créé  sociétés offshore  nom  enfants  chef  gouvernement afin  aider  transférer  argent  étranger.</resumeArticle>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/02/9/2016029_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204252-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Procès</themeArticle>
<titreArticle> jury très féminin  michael jackson</titreArticle>
<resumeArticle> douze membres  jury chargé  juger michael jackson   désignés. huit femmes  font partie  aucun noir   retenu.  star   pop  notamment accusée agression sexuelle   mineur  13 .</resumeArticle>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/02/6/2016026_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204274-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Irak</themeArticle>
<titreArticle>florence  hussein "toujours vivants"</titreArticle>
<resumeArticle>association reporters sans frontières annonce  florence aubenas  hussein hanoun seraient "toujours vivants". cela  cinquante jours   journaliste   guide  disparu  irak.</resumeArticle>
<mailto>stgnews@tf1.fr</mailto>
<auteur>avec AFP</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/47/7/2018477_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204267-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Vatican</themeArticle>
<titreArticle>jean-paul ii opéré " succès"</titreArticle>
<resumeArticle> pape  subi    trachéotomie  aider  respirer. agé  84 ,  souverain pontife   hospitalisé  urgence   seconde fois   mois  hôpital gemelli  rome   suite  problèmes respiratoires.  prochain bulletin  santé  prévu   fin  matinée.</resumeArticle>
<mailto>agautier@tf1.fr</mailto>
<auteur>A.Ga. (d'après AFP)</auteur>
</GROSTITRE>
</LES_GROSTITRES>
<LES_RAPPELS>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Rencontre</themeArticle>
<urlArticle>news/monde/0,,3204172-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>  pression   syrie</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Vatican</themeArticle>
<urlArticle>news/monde/0,,3204078-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>violente polémique autour  livre  pape</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Colombie</themeArticle>
<urlArticle>news/monde/0,,3204086-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>betancourt, otage   </titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Bush - Poutine</themeArticle>
<urlArticle>news/monde/0,,3204192-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>face  face tendu</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>R.U.</themeArticle>
<urlArticle>news/people/0,,3204075-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>camouflet royal  charles  camilla</titreArticle>
</RAPPEL>
</LES_RAPPELS>
</PAGE_LCI>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-02-27.html</FICHIER>
<DATE_PAGE>27/02/2005</DATE_PAGE>
<UNE>
<dateArticle>27/02/2005</dateArticle>
<urlArticle>news/monde/0,,3204809-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> brève apparition  jean-paul ii</titreArticle>
<urlImage>s.tf1.fr/mmdia/i/70/0/2018700_5.jpg</urlImage>
<resumeArticle> pape  béni  foule  signe   croix   chambre   hôpital gemelli  rome.   première fois  jean-paul ii  présidait   prière  angélus.   message lu   nom  archevêque leonardo sandri,   demandé  fidèles  prier  lui.  souverain pontife âgé  84   hospitalisé    avoir subi  trachéotomie.</resumeArticle>
<mailto>agautier@tf1.fr</mailto>
<auteur>A.Ga. (d'après AFP)</auteur>
</UNE>
<LES_VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,3204267-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>jean-paul ii opéré " succès"</titreArticle>
<dateArticle>24/02/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,3204466-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> pape restera muet plusieurs jours</titreArticle>
<dateArticle>25/02/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/economie/0,,3204798-VU5WX0lEIDUy,00.html',700,600,52);"></urlArticle>
<titreArticle> point  état  santé  jean-paul ii</titreArticle>
<dateArticle>26/02/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/economie/0,,3204848-VU5WX0lEIDUy,00.html',700,600,52);"></urlArticle>
<titreArticle>apparition surprise  pape</titreArticle>
<dateArticle>27/02/2005</dateArticle>
</VOIRAUSSI>
</LES_VOIRAUSSI>
<FOCUS>
<dateArticle>27/02/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/69/8/2018698_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204806-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> demi-frère  saddam hussein arrêté</titreArticle>
<resumeArticle>sabaoui ibrahim al-hassan, ex leader baasiste,  soupçonné  diriger  rébellion   gouvernement irakien.</resumeArticle>
<mailto>dstraus@tf1.fr</mailto>
<auteur>D.S. (avec AFP)</auteur>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/65/6/2018656_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204661-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Proche-Orient</themeArticle>
<titreArticle> jihad revendique attentat  tel-aviv</titreArticle>
<resumeArticle> mouvement accuse autorité palestinienne  "collaborer"  israël.     défense israélien met  cause  responsabilité   syrie.</resumeArticle>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/67/8/2018678_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204733-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>USA</themeArticle>
<titreArticle> fin  mystère autour  tueur  série</titreArticle>
<resumeArticle> police  kansas  arrêté  tueur particulièrement sadique  terrorisait  habitants  cet état américain    30 . homme aurait torturé  tué huit personnes entre 1974  1986.</resumeArticle>
<mailto>agautier@tf1.fr</mailto>
<auteur>A.Ga.</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/65/8/2018658_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204664-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Togo</themeArticle>
<titreArticle>gnassingbé rend  fauteuil présidentiel</titreArticle>
<resumeArticle> nouvel homme fort  togo, fils   défunt,  plié   souhait   communauté internationale.</resumeArticle>
<mailto>dstraus@tf1.fr</mailto>
<auteur>D.S. (avec AFP)</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/47/7/2018477_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204466-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Vatican</themeArticle>
<titreArticle> pape restera muet plusieurs jours</titreArticle>
<resumeArticle>  vatican,  souverain pontife respire sans assistance.   passé  nuit calme  lendemain  trachéotomie subie " succès"   suite  difficultés respiratoires.</resumeArticle>
</GROSTITRE>
</LES_GROSTITRES>
<LES_RAPPELS>
<RAPPEL>
<dateArticle>26/02/2005</dateArticle>
<themeArticle>Italie</themeArticle>
<urlArticle>news/monde/0,,3204731-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> forcené maîtrisé   carabiniers</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>24/02/2005</dateArticle>
<themeArticle>Italie</themeArticle>
<urlArticle>news/monde/0,,3204369-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>berlusconi   collimateur   justice</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>24/02/2005</dateArticle>
<themeArticle>Procès</themeArticle>
<urlArticle>news/monde/0,,3204252-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> jury très féminin  michael jackson</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>24/02/2005</dateArticle>
<themeArticle>Irak</themeArticle>
<urlArticle>news/monde/0,,3204274-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>florence  hussein "toujours vivants"</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>24/02/2005</dateArticle>
<themeArticle>Vatican</themeArticle>
<urlArticle>news/monde/0,,3204267-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>jean-paul ii opéré " succès"</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Rencontre</themeArticle>
<urlArticle>news/monde/0,,3204172-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>  pression   syrie</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Vatican</themeArticle>
<urlArticle>news/monde/0,,3204078-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>violente polémique autour  livre  pape</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Colombie</themeArticle>
<urlArticle>news/monde/0,,3204086-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>betancourt, otage   </titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>Bush - Poutine</themeArticle>
<urlArticle>news/monde/0,,3204192-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>face  face tendu</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>23/02/2005</dateArticle>
<themeArticle>R.U.</themeArticle>
<urlArticle>news/people/0,,3204075-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>camouflet royal  charles  camilla</titreArticle>
</RAPPEL>
</LES_RAPPELS>
</PAGE_LCI>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-02-28.html</FICHIER>
<DATE_PAGE>28/02/2005</DATE_PAGE>
<UNE>
<dateArticle>28/02/2005</dateArticle>
<urlArticle>news/monde/0,,3204922-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> milliers  libanais défient  pouvoir</titreArticle>
<urlImage>s.tf1.fr/mmdia/i/73/8/2018738_5.jpg</urlImage>
<resumeArticle>bravant interdiction  pouvoir,  milliers  libanais  rassemblés  aube  beyrouth. ils répondent  appel  opposition  déposé  parlement  motion  censure   cabinet pro-syrien.</resumeArticle>
</UNE>
<FOCUS>
<dateArticle>28/02/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/50/7/2018507_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204931-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>ue : posez vos questions  daniel cohn-bendit</titreArticle>
<resumeArticle> député européen sera invité    13h30  notre  chat consacré   ratification   constitution européenne. vous pouvez lui poser vos questions dès maintenant.</resumeArticle>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/71/2/2018712_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204940-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Vatican</themeArticle>
<titreArticle> pape " bonne condition générale"</titreArticle>
<resumeArticle>  dernier bulletin  santé  pape, jean-paul ii  remet bien   trachéotomie   subie  semaine dernière.   commencé  exercices  rééducation   respiration    parole.</resumeArticle>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/76/2/2018762_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204934-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Irak</themeArticle>
<titreArticle>  100    nouvel attentat</titreArticle>
<resumeArticle>110 personnes   tuées  133 blessées     attentat suicide  hilla,  ville située  100 km  sud  bagdad.</resumeArticle>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/02/9/2016029_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204805-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Etats-Unis</themeArticle>
<titreArticle>michael jackson va pouvoir expliquer</titreArticle>
<resumeArticle> chanteur va pouvoir commencer   répondre  accusations agression sexuelle   mineur, lors   procès  santa maria (californie).</resumeArticle>
<mailto>dstraus@tf1.fr</mailto>
<auteur>AFP</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/71/3/2018713_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204852-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>P-O</themeArticle>
<titreArticle>avertissement  sharon  palestiniens</titreArticle>
<resumeArticle>   israëlien  sommé  autorité palestinienne  "combattre  terrorisme"   mis  cause  syrie  attentat commis   tel-aviv.   syrien  affaires étrangères  nié toute implication      insinué  rôle israël  attaque suicide.</resumeArticle>
<mailto>agautier@tf1.fr</mailto>
<auteur>A.Ga. (avec AFP)</auteur>
</GROSTITRE>
</LES_GROSTITRES>
<LES_RAPPELS>
<RAPPEL>
<dateArticle>27/02/2005</dateArticle>
<themeArticle>Vatican</themeArticle>
<urlArticle>news/monde/0,,3204809-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> signal  pape   fidèles</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>27/02/2005</dateArticle>
<themeArticle>Irak</themeArticle>
<urlArticle>news/monde/0,,3204806-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> demi-frère  saddam hussein arrêté</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>26/02/2005</dateArticle>
<themeArticle>P-O</themeArticle>
<urlArticle>news/monde/0,,3204661-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> jihad revendique attentat  tel-aviv</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>26/02/2005</dateArticle>
<themeArticle>USA</themeArticle>
<urlArticle>news/monde/0,,3204733-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> fin  mystère autour  tueur  série</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>26/02/2005</dateArticle>
<themeArticle>Togo</themeArticle>
<urlArticle>news/monde/0,,3204664-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>gnassingbé rend  fauteuil présidentiel</titreArticle>
</RAPPEL>
</LES_RAPPELS>
</PAGE_LCI>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-03-01.html</FICHIER>
<DATE_PAGE>01/03/2005</DATE_PAGE>
<UNE>
<dateArticle>01/03/2005</dateArticle>
<urlArticle>news/monde/0,,3205126-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> vidéo  florence aubenas</titreArticle>
<urlImage>s.tf1.fr/mmdia/i/86/3/2018863_5.jpg</urlImage>
<resumeArticle>  enregistrement vidéo diffusé  irak mais non daté,  journaliste  libération, disparue   5 janvier, appelle  aide. "ma santé  très mauvaise. je suis également très mal  plan psychologique. aidez-moi,  urgent" lance-t-elle. elle demande notamment appui  député ump didier julia,  origine  polémique lors  affaire  précédents otages , georges malbrunot  christian chesnot.</resumeArticle>
</UNE>
<LES_VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,3200672-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>aubenas,  mois déjà</titreArticle>
<dateArticle>05/02/2005</dateArticle>
</VOIRAUSSI>
</LES_VOIRAUSSI>
<FOCUS>
<dateArticle>01/03/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/50/7/2018507_2.jpg</urlImage>
<urlArticle>news/monde/0,,3204931-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>ue : posez vos questions  daniel cohn-bendit</titreArticle>
<resumeArticle> député européen sera invité    13h30  notre  chat consacré   ratification   constitution européenne. vous pouvez lui poser vos questions dès maintenant.</resumeArticle>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/86/0/2018860_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205127-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Allemagne</themeArticle>
<titreArticle>polémique  ouverture  hôtel   nid aigle hitler</titreArticle>
<resumeArticle>  uns,  occasion  donner   souffle  tourisme local,   autres,  mélange  genres  scandaleux.</resumeArticle>
<mailto>aguillet@tf1.fr</mailto>
<auteur>AG (avec AFP)</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/85/8/2018858_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205124-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Michael Jackson</themeArticle>
<titreArticle>premiers détails  procès</titreArticle>
<resumeArticle>  mois consacré   sélection  jury,  procès  chanteur  véritablement débuté     lecture  arrêt  renvoi   premières accusations concrètes  procureur.</resumeArticle>
<mailto>faubert@tf1.fr</mailto>
<auteur>F.A., avec AFP</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/81/5/2018815_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205033-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Liban</themeArticle>
<titreArticle> rue  chuter  pouvoir</titreArticle>
<resumeArticle>   libanais omar karamé  annoncé, ,  démission alors   parlement devait examiner  motion  censure déposée  opposition anti-syrienne    milliers  personnes défilaient  beyrouth.</resumeArticle>
</GROSTITRE>
</LES_GROSTITRES>
<LES_RAPPELS>
<RAPPEL>
<dateArticle>28/02/2005</dateArticle>
<themeArticle>Irak</themeArticle>
<urlArticle>news/monde/0,,3204934-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>  100    nouvel attentat</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>28/02/2005</dateArticle>
<themeArticle>Vatican</themeArticle>
<urlArticle>news/monde/0,,3204940-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> pape " bonne condition générale"</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>27/02/2005</dateArticle>
<themeArticle>P-O</themeArticle>
<urlArticle>news/monde/0,,3204852-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>avertissement  sharon  palestiniens</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>27/02/2005</dateArticle>
<themeArticle>Irak</themeArticle>
<urlArticle>news/monde/0,,3204806-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> demi-frère  saddam hussein arrêté</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>26/02/2005</dateArticle>
<themeArticle>P-O</themeArticle>
<urlArticle>news/monde/0,,3204661-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> jihad revendique attentat  tel-aviv</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>26/02/2005</dateArticle>
<themeArticle>USA</themeArticle>
<urlArticle>news/monde/0,,3204733-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> fin  mystère autour  tueur  série</titreArticle>
</RAPPEL>
</LES_RAPPELS>
</PAGE_LCI>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-03-03.html</FICHIER>
<DATE_PAGE>03/03/2005</DATE_PAGE>
<UNE>
<dateArticle>03/03/2005</dateArticle>
<urlArticle>news/monde/0,,3205560-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>bali : peine légère  bachir</titreArticle>
<urlImage>s.tf1.fr/mmdia/i/99/8/538998_5.jpg</urlImage>
<resumeArticle> chef religieux indonésien abou bakar bachir   condamné       demi  prison ferme   rôle   attentats  bali  2002.    revanche  blanchi  affaire  attaque  hôtel marriott  jakarta  2003.</resumeArticle>
</UNE>
<LES_VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,960358-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>bali :  suspect avoue</titreArticle>
<dateArticle>08/11/2002</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,964955-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> cerveau  attentat  bali passe  aveux</titreArticle>
<dateArticle>22/11/2002</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,1062351-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>début  procès  attentat  bali</titreArticle>
<dateArticle>12/05/2003</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,1350143-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>bali : deuxième condamnation  mort</titreArticle>
<dateArticle>10/09/2003</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,3180247-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> islamiste bachir inculpé   attentats  bali</titreArticle>
<dateArticle>16/10/2004</dateArticle>
</VOIRAUSSI>
</LES_VOIRAUSSI>
<FOCUS>
<dateArticle>03/03/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/85/0/874850_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205442-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> "jilbab" islamique autorisé  école</titreArticle>
<resumeArticle>  longue bataille judiciaire,  lycéenne musulmane  obtenu  droit  porter  école  "jilbab",  longue robe   laisse voir   mains   visage. elle était défendue  cherie blair,  femme   .</resumeArticle>
<mailto>faubert@tf1.fr</mailto>
<auteur>Fabrice AUBERT</auteur>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/24/1/2019241_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205642-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Aubenas</themeArticle>
<titreArticle>julia pose  conditions</titreArticle>
<resumeArticle>sollicité     , didier julia  indiqué  avoir eu  entretien   directeur général   dgse   cas  florence aubenas. mais,  préalable   coopération,  réclame  levée  contrôle judiciaire   collaborateurs.</resumeArticle>
</GROSTITRE>
</LES_GROSTITRES>
<LES_RAPPELS>
<RAPPEL>
<dateArticle>02/03/2005</dateArticle>
<themeArticle>Aubenas</themeArticle>
<urlArticle>news/monde/0,,3205475-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>raffarin demande  julia  collaborer</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>01/03/2005</dateArticle>
<themeArticle>Procès Jackson</themeArticle>
<urlArticle>news/monde/0,,3205325-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>audition  témoin crucial</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>02/03/2005</dateArticle>
<themeArticle>Liban</themeArticle>
<urlArticle>news/monde/0,,3205333-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> syrie promet   retirer</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>01/03/2005</dateArticle>
<themeArticle>USA</themeArticle>
<urlArticle>news/monde/0,,3205249-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> mineurs  seront  exécutés</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>01/03/2005</dateArticle>
<themeArticle>Allemagne</themeArticle>
<urlArticle>news/monde/0,,3205127-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>polémique  ouverture  hôtel   nid aigle hitler</titreArticle>
</RAPPEL>
</LES_RAPPELS>
</PAGE_LCI>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-03-04.html</FICHIER>
<DATE_PAGE>04/03/2005</DATE_PAGE>
<UNE>
<dateArticle>04/03/2005</dateArticle>
<urlArticle>news/monde/0,,3205754-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>ukraine : ex-  intérieur retrouvé suicidé</titreArticle>
<urlImage>s.tf1.fr/mmdia/i/29/4/2019294_5.gif"</urlImage>
<resumeArticle>iouri kravtchenko devait témoigner     cadre  affaire  assassinat  journaliste opposition gueorgui gongadzé.    retrouvé mort,   apparemment tiré  balle   tête.</resumeArticle>
</UNE>
<FOCUS>
<dateArticle>04/03/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/50/7/2018507_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205649-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>cohn-bendit : "europe, dernière utopie"</titreArticle>
<resumeArticle>invité    notre  chat consacré  référendum   constitution,  député européen écologiste  dit confiant   victoire  "oui".  lui, europe   effet  "dernière utopie  laquelle on mérite   battre".</resumeArticle>
<mailto>faubert@tf1.fr</mailto>
<auteur>Fabrice AUBERT et R.P.</auteur>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/54/1/19541_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205751-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Italie</themeArticle>
<titreArticle> famille, rempart  exclusion</titreArticle>
<resumeArticle> italie,  notamment  rome,  grande majorité  sans-abris   immigrés.  lien familial  amical jouant  effet  rôle  bouclier  exclusion,   très rare   italiens  retrouvent   rue.</resumeArticle>
<mailto>faubert@tf1.fr</mailto>
<auteur>Maurice OLIVARI</auteur>
</GROSTITRE>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/25/9/2019259_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205642-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Aubenas</themeArticle>
<titreArticle>appel  raffarin  ravisseurs aubenas</titreArticle>
<resumeArticle>   , toute demande  didier julia agir " manière indépendante"  faveur  florence aubenas  "inacceptable". élu ump ainsi écarté, jean-pierre raffarin, adressant  ravisseurs, leur  demandé   contacter " seuls services officiels   "  "engager  discussions".</resumeArticle>
</GROSTITRE>
</LES_GROSTITRES>
<LES_RAPPELS>
<RAPPEL>
<dateArticle>03/03/2005</dateArticle>
<themeArticle>Attentat de Bali</themeArticle>
<urlArticle>news/monde/0,,3205560-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>peine légère  bachir</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>02/03/2005</dateArticle>
<themeArticle>Royaume-Uni</themeArticle>
<urlArticle>news/monde/0,,3205442-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> "jilbab" islamique autorisé  école</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>01/03/2005</dateArticle>
<themeArticle>USA</themeArticle>
<urlArticle>news/monde/0,,3205249-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> mineurs  seront  exécutés</titreArticle>
</RAPPEL>
<RAPPEL>
<dateArticle>01/03/2005</dateArticle>
<themeArticle>Allemagne</themeArticle>
<urlArticle>news/monde/0,,3205127-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>polémique  ouverture  hôtel   nid aigle hitler</titreArticle>
</RAPPEL>
</LES_RAPPELS>
</PAGE_LCI>
<PAGE_LCI>
<FICHIER>LCINORM_SPLIT/lci-monde-2005-03-05.html</FICHIER>
<DATE_PAGE>05/03/2005</DATE_PAGE>
<UNE>
<dateArticle>05/03/2005</dateArticle>
<urlArticle>news/monde/0,,3205941-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle> vie sauvée,  vie perdue</titreArticle>
<urlImage>s.tf1.fr/mmdia/i/40/1/2019401_5.jpg</urlImage>
<resumeArticle> joie   libération  giuliana sgrena, retenue  otage durant  mois  irak,   endeuillée   mort    libérateur tué   tirs américains,  membre  services spéciaux  traité  "héros" samedi   presse   péninsule.  journaliste  arrivée samedi   italie où elle doit  réopérée   clavicule.</resumeArticle>
<mailto>dstraus@tf1.fr</mailto>
<auteur>AFP</auteur>
</UNE>
<LES_VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/monde/0,,3205861-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>libération chaotique  giuliana sgrena</titreArticle>
<dateArticle>04/03/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/newsthemes/monde/0,,3205869-VU5WX0lEIDUy,00.html',740,580,52);"></urlArticle>
<titreArticle>giuliana sgrena libre</titreArticle>
<dateArticle>04/03/2005</dateArticle>
</VOIRAUSSI>
<VOIRAUSSI>
<urlArticle>news/newsthemes/france/0,,3205875-VU5WX0lEIDUy,00.html',740,580,52);"></urlArticle>
<titreArticle>retour   mobilisation  florence aubenas</titreArticle>
<dateArticle>04/03/2005</dateArticle>
</VOIRAUSSI>
</LES_VOIRAUSSI>
<FOCUS>
<dateArticle>05/03/2005</dateArticle>
<urlImage>s.tf1.fr/mmdia/i/50/7/2018507_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205649-VU5WX0lEIDUy,00.html</urlArticle>
<titreArticle>cohn-bendit : "europe, dernière utopie"</titreArticle>
<resumeArticle>invité    notre  chat consacré  référendum   constitution,  député européen écologiste  dit confiant   victoire  "oui".  lui, europe   effet  "dernière utopie  laquelle on mérite   battre".</resumeArticle>
<mailto>faubert@tf1.fr</mailto>
<auteur>Fabrice AUBERT et R.P.</auteur>
</FOCUS>
<LES_GROSTITRES>
<GROSTITRE>
<urlImage>s.tf1.fr/mmdia/i/69/1/851691_2.jpg</urlImage>
<urlArticle>news/monde/0,,3205944-VU5WX0lEIDUy,00.html</urlArticle>
<themeArticle>Côté d'Ivoire</themeArticle>
<titreArticle> soldats  tués accidentellement</titreArticle>
<resumeArticle>  hommes  perdu  vie  explosion accidentelle  local  munitions  abidjan.  troisième   grièvement blessé.</resumeArticle>
<mailto>dstraus@tf1.fr</mailto>
<auteur>David STRAUS</auteur>
</GROSTITRE>
<GROSTITRE>